export enum Systems {
  FE_AUTH = 'FE_AUTH',
  BE_AUTH = 'BE_AUTH',
  FE_TOURNAMENTS = 'FE_TOURNAMENTS',
  BE_TOURNAMENTS = 'BE_TOURNAMENTS',
  FE_USERS = 'FE_USERS',
  BE_USERS = 'BE_USERS',
  FE_BILLING = 'FE_BILLING',
  BE_BILLING = 'BE_BILLING',
}
